# Application name
spring:
  application:
    name: payment-service
  # Config import
  config:
    import: configserver:http://localhost:8888
  # Config profile
  cloud:
    config:
      profile: service
  # DB config
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/payment-service-db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
