# Application name
spring:
  application:
    name: registry
# Config import
  config:
    import: configserver:http://localhost:8888
# Server port
server:
  port: 8761
# This microservice is not a client, so the value is false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false