spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vladimirchavkin/primitive-banking-system
          clone-on-start: true
          username: vladimirchavkin
          password: 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
          basedir: file://c:/tmp/javams/bank
          default-label: main
          try-master-branch: false

server:
  port: 8888